package provider

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/joelfernandes23/terraform-provider-kargo/internal/client"
)

var (
	_ resource.Resource                = &ProjectConfigResource{}
	_ resource.ResourceWithImportState = &ProjectConfigResource{}
)

type ProjectConfigResource struct {
	client client.KargoClient
}

type ProjectConfigResourceModel struct {
	Project           types.String                `tfsdk:"project"`
	ID                types.String                `tfsdk:"id"`
	PromotionPolicies []ProjectConfigPolicyModel  `tfsdk:"promotion_policy"`
	WebhookReceivers  []ProjectConfigWebhookModel `tfsdk:"webhook_receiver"`
	WebhookEndpoints  types.List                  `tfsdk:"webhook_endpoint"`
}

type ProjectConfigPolicyModel struct {
	StageSelector        *ProjectConfigSelectorModel `tfsdk:"stage_selector"`
	AutoPromotionEnabled types.Bool                  `tfsdk:"auto_promotion_enabled"`
}

type ProjectConfigSelectorModel struct {
	Name             types.String                        `tfsdk:"name"`
	MatchLabels      types.Map                           `tfsdk:"match_labels"`
	MatchExpressions []ProjectConfigMatchExpressionModel `tfsdk:"match_expression"`
}

type ProjectConfigMatchExpressionModel struct {
	Key      types.String `tfsdk:"key"`
	Operator types.String `tfsdk:"operator"`
	Values   types.List   `tfsdk:"values"`
}

type ProjectConfigWebhookModel struct {
	Name            types.String         `tfsdk:"name"`
	Type            types.String         `tfsdk:"type"`
	SecretName      types.String         `tfsdk:"secret_name"`
	VirtualRepoName types.String         `tfsdk:"virtual_repo_name"`
	GenericActions  jsontypes.Normalized `tfsdk:"generic_actions"`
}

type ProjectConfigEndpointModel struct {
	Name types.String `tfsdk:"name"`
	Path types.String `tfsdk:"path"`
	URL  types.String `tfsdk:"url"`
}

func NewProjectConfigResource() resource.Resource {
	return &ProjectConfigResource{}
}

func (r *ProjectConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_config"
}

func (r *ProjectConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Provides a Kargo ProjectConfig resource.",
		Attributes: map[string]schema.Attribute{
			"project": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators:  rfc1123NameValidators(),
				Description: "Name of the Kargo Project.",
			},
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Description: "Name of the Kargo Project.",
			},
			"webhook_endpoint": schema.ListNestedAttribute{
				Computed:    true,
				Sensitive:   true,
				Description: "Webhook endpoints generated by Kargo.",
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{Computed: true, Description: "Name of the webhook receiver."},
					"path": schema.StringAttribute{Computed: true, Sensitive: true, Description: "Path generated for the webhook receiver."},
					"url":  schema.StringAttribute{Computed: true, Sensitive: true, Description: "Complete URL to give to the service sending the webhook."},
				}},
			},
		},
		Blocks: map[string]schema.Block{
			"promotion_policy": schema.ListNestedBlock{
				Description: "Promotion policies for the Project. Policies are evaluated in order and the first matching policy applies.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"auto_promotion_enabled": schema.BoolAttribute{Optional: true, Description: "Whether automatic promotion is enabled for matching Stages. Defaults to `false`."},
					},
					Blocks: map[string]schema.Block{
						"stage_selector": schema.SingleNestedBlock{
							Description: "Selector for Stages to which the promotion policy applies.",
							Attributes: map[string]schema.Attribute{
								"name":         schema.StringAttribute{Optional: true, Description: "Stage name to match. Prefix a pattern with `glob:`, `regex:`, or `regexp:`."},
								"match_labels": schema.MapAttribute{Optional: true, ElementType: types.StringType, Description: "Labels that must be present on a stage."},
							},
							Blocks: map[string]schema.Block{
								"match_expression": schema.ListNestedBlock{
									NestedObject: schema.NestedBlockObject{Attributes: map[string]schema.Attribute{
										"key":      schema.StringAttribute{Required: true, Description: "Stage label to check."},
										"operator": schema.StringAttribute{Required: true, Description: "How to compare the stage label. Valid values are `In`, `NotIn`, `Exists`, and `DoesNotExist`.", Validators: []validator.String{stringvalidator.OneOf("In", "NotIn", "Exists", "DoesNotExist")}},
										"values":   schema.ListAttribute{Optional: true, ElementType: types.StringType, Description: "Label values used with the `In` and `NotIn` operators."},
									}},
								},
							},
						},
					},
				},
			},
			"webhook_receiver": schema.ListNestedBlock{
				Description: "Webhook receivers for the Project.",
				NestedObject: schema.NestedBlockObject{Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{Required: true, Description: "Name for this webhook receiver.", Validators: rfc1123NameValidators()},
					"type": schema.StringAttribute{Required: true, Description: "Service that will send the webhook.", Validators: []validator.String{stringvalidator.OneOf(
						"artifactory", "azure", "bitbucket", "dockerhub", "generic", "gitea", "github", "gitlab", "harbor", "quay",
					)}},
					"secret_name":       schema.StringAttribute{Required: true, Description: "Name of an existing Secret in the project containing the webhook credentials.", Validators: rfc1123NameValidators()},
					"virtual_repo_name": schema.StringAttribute{Optional: true, Description: "Name of the Artifactory virtual repository. Valid when `type` is `artifactory`."},
					"generic_actions": schema.StringAttribute{
						Optional:    true,
						CustomType:  jsontypes.NormalizedType{},
						Description: "Actions for a generic webhook receiver in JSON format. Required when `type` is `generic`.",
					},
				}},
			},
		},
	}
}

func (r *ProjectConfigResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(client.KargoClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected client.KargoClient, got: %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *ProjectConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ProjectConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	spec, err := expandProjectConfig(ctx, &data)
	if err != nil {
		resp.Diagnostics.AddError("Invalid project configuration", err.Error())
		return
	}
	config, err := r.client.CreateProjectConfig(ctx, data.Project.ValueString(), spec)
	if err != nil {
		resp.Diagnostics.AddError("Failed to create project configuration", err.Error())
		return
	}
	if config == nil {
		resp.Diagnostics.AddError("Failed to create project configuration", "Kargo returned no ProjectConfig after creation.")
		return
	}
	newData := flattenProjectConfig(ctx, data.Project.ValueString(), config, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &newData)...)
}

func (r *ProjectConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ProjectConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	config, err := r.client.GetProjectConfig(ctx, data.Project.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Failed to read project configuration", err.Error())
		return
	}
	if config == nil {
		resp.State.RemoveResource(ctx)
		return
	}
	newData := flattenProjectConfig(ctx, data.Project.ValueString(), config, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &newData)...)
}

func (r *ProjectConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ProjectConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	spec, err := expandProjectConfig(ctx, &data)
	if err != nil {
		resp.Diagnostics.AddError("Invalid project configuration", err.Error())
		return
	}
	config, err := r.client.UpdateProjectConfig(ctx, data.Project.ValueString(), spec)
	if err != nil {
		resp.Diagnostics.AddError("Failed to update project configuration", err.Error())
		return
	}
	if config == nil {
		resp.Diagnostics.AddError("Failed to update project configuration", "Kargo returned no ProjectConfig after update.")
		return
	}
	newData := flattenProjectConfig(ctx, data.Project.ValueString(), config, &data)
	resp.Diagnostics.Append(resp.State.Set(ctx, &newData)...)
}

func (r *ProjectConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ProjectConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteProjectConfig(ctx, data.Project.ValueString()); err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Failed to delete project configuration", err.Error())
	}
}

func (r *ProjectConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if req.ID == "" || strings.Contains(req.ID, "/") {
		resp.Diagnostics.AddError("Invalid ProjectConfig import ID", "Expected the Project name.")
		return
	}
	config, err := r.client.GetProjectConfig(ctx, req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Failed to import project configuration", err.Error())
		return
	}
	if config == nil {
		resp.Diagnostics.AddError("ProjectConfig not found", fmt.Sprintf("ProjectConfig %q does not exist.", req.ID))
		return
	}
	data := flattenProjectConfig(ctx, req.ID, config, nil)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func expandProjectConfig(ctx context.Context, data *ProjectConfigResourceModel) (client.ProjectConfigSpec, error) {
	spec := client.ProjectConfigSpec{
		PromotionPolicies: make([]client.PromotionPolicy, 0, len(data.PromotionPolicies)),
		WebhookReceivers:  make([]client.WebhookReceiverConfig, 0, len(data.WebhookReceivers)),
	}
	seenExact := map[string]int{}
	for i, policy := range data.PromotionPolicies {
		if policy.StageSelector == nil {
			return spec, fmt.Errorf("promotion_policy %d must contain stage_selector", i)
		}
		selector, err := expandProjectConfigSelector(ctx, policy.StageSelector)
		if err != nil {
			return spec, fmt.Errorf("promotion_policy %d: %w", i, err)
		}
		if selector.Name != "" && !strings.Contains(selector.Name, ":") {
			if first, ok := seenExact[selector.Name]; ok {
				return spec, fmt.Errorf("promotion_policy %d duplicates exact stage name from promotion_policy %d", i, first)
			}
			seenExact[selector.Name] = i
		}
		spec.PromotionPolicies = append(spec.PromotionPolicies, client.PromotionPolicy{
			StageSelector:        selector,
			AutoPromotionEnabled: policy.AutoPromotionEnabled.ValueBool(),
		})
	}

	seenReceivers := map[string]int{}
	for i, receiver := range data.WebhookReceivers {
		name := receiver.Name.ValueString()
		if first, ok := seenReceivers[name]; ok {
			return spec, fmt.Errorf("webhook_receiver %d duplicates name from webhook_receiver %d", i, first)
		}
		seenReceivers[name] = i
		expanded, err := expandWebhookReceiver(receiver)
		if err != nil {
			return spec, fmt.Errorf("webhook_receiver %d: %w", i, err)
		}
		spec.WebhookReceivers = append(spec.WebhookReceivers, expanded)
	}
	return spec, nil
}

func expandProjectConfigSelector(ctx context.Context, model *ProjectConfigSelectorModel) (client.PromotionPolicySelector, error) {
	selector := client.PromotionPolicySelector{Name: valueString(model.Name)}
	if !model.MatchLabels.IsNull() && !model.MatchLabels.IsUnknown() {
		if diags := model.MatchLabels.ElementsAs(ctx, &selector.MatchLabels, false); diags.HasError() {
			return selector, fmt.Errorf("invalid match_labels: %s", diags)
		}
	}
	for i, expression := range model.MatchExpressions {
		values := []string{}
		if !expression.Values.IsNull() && !expression.Values.IsUnknown() {
			if diags := expression.Values.ElementsAs(ctx, &values, false); diags.HasError() {
				return selector, fmt.Errorf("match_expression %d has invalid values: %s", i, diags)
			}
		}
		operator := expression.Operator.ValueString()
		if (operator == "In" || operator == "NotIn") && len(values) == 0 {
			return selector, fmt.Errorf("match_expression %d operator %s requires values", i, operator)
		}
		if (operator == "Exists" || operator == "DoesNotExist") && len(values) != 0 {
			return selector, fmt.Errorf("match_expression %d operator %s must not have values", i, operator)
		}
		selector.MatchExpressions = append(selector.MatchExpressions, client.LabelSelectorRequirement{
			Key: expression.Key.ValueString(), Operator: operator, Values: values,
		})
	}
	if selector.Name == "" && len(selector.MatchLabels) == 0 && len(selector.MatchExpressions) == 0 {
		return selector, fmt.Errorf("stage_selector must set name, match_labels, or match_expression")
	}
	if strings.HasPrefix(selector.Name, "regex:") || strings.HasPrefix(selector.Name, "regexp:") {
		pattern := strings.SplitN(selector.Name, ":", 2)[1]
		if _, err := regexp.Compile(pattern); err != nil {
			return selector, fmt.Errorf("invalid stage selector pattern: %w", err)
		}
	} else if strings.Contains(selector.Name, ":") && !strings.HasPrefix(selector.Name, "glob:") {
		return selector, fmt.Errorf("stage selector pattern must use a glob, regex, or regexp prefix")
	}
	return selector, nil
}

func expandWebhookReceiver(model ProjectConfigWebhookModel) (client.WebhookReceiverConfig, error) {
	result := client.WebhookReceiverConfig{Name: model.Name.ValueString()}
	secret := client.WebhookSecretRefConfig{SecretRef: client.LocalObjectReference{Name: model.SecretName.ValueString()}}
	typ := model.Type.ValueString()
	hasVirtualRepo := !model.VirtualRepoName.IsNull() && !model.VirtualRepoName.IsUnknown()
	hasGenericActions := !model.GenericActions.IsNull() && !model.GenericActions.IsUnknown()
	if typ != "artifactory" && hasVirtualRepo {
		return result, fmt.Errorf("virtual_repo_name is valid only for type artifactory")
	}
	if typ != "generic" && hasGenericActions {
		return result, fmt.Errorf("generic_actions is valid only for type generic")
	}
	switch typ {
	case "artifactory":
		result.Artifactory = &client.ArtifactoryWebhookConfig{SecretRef: secret.SecretRef, VirtualRepoName: valueString(model.VirtualRepoName)}
	case "azure":
		result.Azure = &secret
	case "bitbucket":
		result.Bitbucket = &secret
	case "dockerhub":
		result.DockerHub = &secret
	case "gitea":
		result.Gitea = &secret
	case "github":
		result.GitHub = &secret
	case "gitlab":
		result.GitLab = &secret
	case "harbor":
		result.Harbor = &secret
	case "quay":
		result.Quay = &secret
	case "generic":
		if !hasGenericActions {
			return result, fmt.Errorf("generic_actions is required for type generic")
		}
		var actions []client.GenericWebhookAction
		if err := json.Unmarshal([]byte(model.GenericActions.ValueString()), &actions); err != nil {
			return result, fmt.Errorf("decoding generic_actions: %w", err)
		}
		if len(actions) == 0 {
			return result, fmt.Errorf("generic_actions must contain at least one action")
		}
		for i, action := range actions {
			if action.Action != "Refresh" {
				return result, fmt.Errorf("generic action %d must use action Refresh", i)
			}
			if len(action.TargetSelectionCriteria) == 0 {
				return result, fmt.Errorf("generic action %d must contain targetSelectionCriteria", i)
			}
			for j, target := range action.TargetSelectionCriteria {
				if target.Kind != "Warehouse" {
					return result, fmt.Errorf("generic action %d target %d must use kind Warehouse for Kargo v1.9.5", i, j)
				}
				if target.Name == "" && target.LabelSelector == nil && target.IndexSelector == nil {
					return result, fmt.Errorf("generic action %d target %d must set name, labelSelector, or indexSelector", i, j)
				}
				if target.IndexSelector != nil {
					if len(target.IndexSelector.MatchIndices) == 0 {
						return result, fmt.Errorf("generic action %d target %d indexSelector must contain matchIndices", i, j)
					}
					for k, index := range target.IndexSelector.MatchIndices {
						if index.Key != "subscribedURLs" && index.Key != "receiverPaths" {
							return result, fmt.Errorf("generic action %d target %d index %d has unsupported key %q", i, j, k, index.Key)
						}
						if index.Operator != "Equals" && index.Operator != "NotEquals" {
							return result, fmt.Errorf("generic action %d target %d index %d has unsupported operator %q", i, j, k, index.Operator)
						}
						if index.Value == "" {
							return result, fmt.Errorf("generic action %d target %d index %d must set value", i, j, k)
						}
					}
				}
			}
		}
		result.Generic = &client.GenericWebhookReceiverConfig{SecretRef: secret.SecretRef, Actions: actions}
	default:
		return result, fmt.Errorf("unsupported receiver type %q", typ)
	}
	return result, nil
}

func flattenProjectConfig(ctx context.Context, project string, config *client.ProjectConfig, prior *ProjectConfigResourceModel) ProjectConfigResourceModel {
	resolvedProject := config.Metadata.Namespace
	if resolvedProject == "" {
		resolvedProject = project
	}
	data := ProjectConfigResourceModel{
		Project:           types.StringValue(resolvedProject),
		ID:                types.StringValue(resolvedProject),
		PromotionPolicies: make([]ProjectConfigPolicyModel, 0, len(config.Spec.PromotionPolicies)),
		WebhookReceivers:  make([]ProjectConfigWebhookModel, 0, len(config.Spec.WebhookReceivers)),
	}
	for _, policy := range config.Spec.PromotionPolicies {
		labels, _ := types.MapValueFrom(ctx, types.StringType, policy.StageSelector.MatchLabels)
		selectorName := types.StringNull()
		if policy.StageSelector.Name != "" {
			selectorName = types.StringValue(policy.StageSelector.Name)
		}
		expressions := make([]ProjectConfigMatchExpressionModel, 0, len(policy.StageSelector.MatchExpressions))
		for _, expression := range policy.StageSelector.MatchExpressions {
			values, _ := types.ListValueFrom(ctx, types.StringType, expression.Values)
			expressions = append(expressions, ProjectConfigMatchExpressionModel{
				Key: types.StringValue(expression.Key), Operator: types.StringValue(expression.Operator), Values: values,
			})
		}
		data.PromotionPolicies = append(data.PromotionPolicies, ProjectConfigPolicyModel{
			StageSelector: &ProjectConfigSelectorModel{
				Name: selectorName, MatchLabels: labels, MatchExpressions: expressions,
			},
			AutoPromotionEnabled: types.BoolValue(policy.AutoPromotionEnabled),
		})
	}
	for _, receiver := range config.Spec.WebhookReceivers {
		data.WebhookReceivers = append(data.WebhookReceivers, flattenWebhookReceiver(receiver))
	}
	endpoints := make([]ProjectConfigEndpointModel, 0, len(config.Status.WebhookReceivers))
	for _, endpoint := range config.Status.WebhookReceivers {
		endpoints = append(endpoints, ProjectConfigEndpointModel{
			Name: types.StringValue(endpoint.Name), Path: types.StringValue(endpoint.Path), URL: types.StringValue(endpoint.URL),
		})
	}
	data.WebhookEndpoints, _ = types.ListValueFrom(ctx, projectConfigEndpointObjectType(), endpoints)
	_ = prior
	return data
}

func projectConfigEndpointObjectType() types.ObjectType {
	return types.ObjectType{AttrTypes: map[string]attr.Type{
		"name": types.StringType,
		"path": types.StringType,
		"url":  types.StringType,
	}}
}

func flattenWebhookReceiver(receiver client.WebhookReceiverConfig) ProjectConfigWebhookModel {
	model := ProjectConfigWebhookModel{
		Name: types.StringValue(receiver.Name), VirtualRepoName: types.StringNull(), GenericActions: jsontypes.NewNormalizedNull(),
	}
	setSecret := func(typ string, ref client.LocalObjectReference) {
		model.Type = types.StringValue(typ)
		model.SecretName = types.StringValue(ref.Name)
	}
	switch {
	case receiver.Artifactory != nil:
		setSecret("artifactory", receiver.Artifactory.SecretRef)
		if receiver.Artifactory.VirtualRepoName != "" {
			model.VirtualRepoName = types.StringValue(receiver.Artifactory.VirtualRepoName)
		}
	case receiver.Azure != nil:
		setSecret("azure", receiver.Azure.SecretRef)
	case receiver.Bitbucket != nil:
		setSecret("bitbucket", receiver.Bitbucket.SecretRef)
	case receiver.DockerHub != nil:
		setSecret("dockerhub", receiver.DockerHub.SecretRef)
	case receiver.Generic != nil:
		setSecret("generic", receiver.Generic.SecretRef)
		if raw, err := json.Marshal(receiver.Generic.Actions); err == nil {
			model.GenericActions = jsontypes.NewNormalizedValue(string(raw))
		}
	case receiver.Gitea != nil:
		setSecret("gitea", receiver.Gitea.SecretRef)
	case receiver.GitHub != nil:
		setSecret("github", receiver.GitHub.SecretRef)
	case receiver.GitLab != nil:
		setSecret("gitlab", receiver.GitLab.SecretRef)
	case receiver.Harbor != nil:
		setSecret("harbor", receiver.Harbor.SecretRef)
	case receiver.Quay != nil:
		setSecret("quay", receiver.Quay.SecretRef)
	}
	return model
}
