package provider

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/joelfernandes23/terraform-provider-kargo/internal/client"
)

var _ datasource.DataSource = &ProjectConfigDataSource{}

type ProjectConfigDataSource struct {
	client client.KargoClient
}

type ProjectConfigDataSourceModel struct {
	Project           types.String         `tfsdk:"project"`
	ID                types.String         `tfsdk:"id"`
	PromotionPolicies jsontypes.Normalized `tfsdk:"promotion_policies"`
	WebhookReceivers  jsontypes.Normalized `tfsdk:"webhook_receivers"`
	WebhookEndpoints  types.List           `tfsdk:"webhook_endpoint"`
}

func NewProjectConfigDataSource() datasource.DataSource {
	return &ProjectConfigDataSource{}
}

func (d *ProjectConfigDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_config"
}

func (d *ProjectConfigDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Reads a Kargo ProjectConfig, including promotion policies, webhook receivers, and generated endpoints.",
		Attributes: map[string]schema.Attribute{
			"project": schema.StringAttribute{Required: true, Validators: rfc1123NameValidators(), Description: "The Kargo project."},
			"id":      schema.StringAttribute{Computed: true, Description: "The ProjectConfig identifier, equal to the project name."},
			"promotion_policies": schema.StringAttribute{
				Computed: true, CustomType: jsontypes.NormalizedType{}, Description: "Promotion policies as normalized JSON in Kargo API form.",
			},
			"webhook_receivers": schema.StringAttribute{
				Computed: true, CustomType: jsontypes.NormalizedType{}, Description: "Webhook receiver configuration as normalized JSON in Kargo API form. Secret values are not returned by Kargo.",
			},
			"webhook_endpoint": schema.ListNestedAttribute{
				Computed: true, Sensitive: true, Description: "Webhook endpoints generated by Kargo.",
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{Computed: true},
					"path": schema.StringAttribute{Computed: true, Sensitive: true},
					"url":  schema.StringAttribute{Computed: true, Sensitive: true},
				}},
			},
		},
	}
}

func (d *ProjectConfigDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(client.KargoClient)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected client.KargoClient, got: %T", req.ProviderData))
		return
	}
	d.client = c
}

func (d *ProjectConfigDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectConfigDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	project := data.Project.ValueString()
	config, err := d.client.GetProjectConfig(ctx, project)
	if err != nil {
		if client.IsNotFound(err) {
			resp.Diagnostics.AddError("ProjectConfig not found", fmt.Sprintf("ProjectConfig for project %q does not exist.", project))
			return
		}
		resp.Diagnostics.AddError("Failed to read project configuration", err.Error())
		return
	}
	if config == nil {
		resp.Diagnostics.AddError("ProjectConfig not found", fmt.Sprintf("ProjectConfig for project %q does not exist.", project))
		return
	}
	policies, err := json.Marshal(config.Spec.PromotionPolicies)
	if err != nil {
		resp.Diagnostics.AddError("Failed to encode promotion policies", err.Error())
		return
	}
	receivers, err := json.Marshal(config.Spec.WebhookReceivers)
	if err != nil {
		resp.Diagnostics.AddError("Failed to encode webhook receivers", err.Error())
		return
	}
	data.ID = types.StringValue(project)
	data.PromotionPolicies = jsontypes.NewNormalizedValue(string(policies))
	data.WebhookReceivers = jsontypes.NewNormalizedValue(string(receivers))
	endpoints := make([]ProjectConfigEndpointModel, 0, len(config.Status.WebhookReceivers))
	for _, endpoint := range config.Status.WebhookReceivers {
		endpoints = append(endpoints, ProjectConfigEndpointModel{
			Name: types.StringValue(endpoint.Name), Path: types.StringValue(endpoint.Path), URL: types.StringValue(endpoint.URL),
		})
	}
	data.WebhookEndpoints, _ = types.ListValueFrom(ctx, projectConfigEndpointObjectType(), endpoints)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
